stages:
  - build

typst-compile:
  stage: build
  image: ghcr.io/typst/typst:latest
  script:
    - apk add font-roboto
    - |+
      for file in ./tshirtd.*.typ; do
        typst compile -f svg $file
        typst compile -f pdf $file
      done
  artifacts:
    expire_in: 1 week
    paths:
      - ./tshirtd.*.svg
      - ./tshirtd.*.pdf
