stages:
  - build

typst-compile:
  stage: build
  image: ghcr.io/typst/typst:latest
  script:
    - apk add font-roboto
    - |+
      for file in ./src/tshirtd.*.typ; do
		typst compile -f svg $file $(basename -s .typ $file).svg
		typst compile -f pdf $file $(basename -s .typ $file).pdf
      done
  artifacts:
    expire_in: 1 week
    paths:
      - ./build/tshirtd.*.svg
      - ./build/tshirtd.*.pdf
