stages:
  - build

typst-compile:
  stage: build
  image:
    name: ghcr.io/typst/typst:latest
    entrypoint: [""]
  script:
    - apk add font-roboto
    - ./build.sh
  artifacts:
    expire_in: 1 week
    paths:
      - ./build/
