stages:
  - build

typst-compile:
  stage: build
  image: ghcr.io/typst/typst:latest
  script:
    - apk add font-roboto
    - |+
      ./build.sh
  artifacts:
    expire_in: 1 week
    paths:
      - ./build
